# promise & fetch

교재: Do it! 웹표준의정석
작업중: In progress
태그: Dev, 웹&모바일, 웹프로그래밍기초
학습일: 12/23/2022

**환경설정**

ex09 node_module

```bash
npm install express
node app.js
```

### promise 객체

비동기 작업을 편리하게 다루는 문법

new Promist(executor)

- executor 생성자가 실행시킬 함수
- executor 실행한 비동기 작업 결과를 통지 받는다.
    
    : 생성자가 실행시킬 함수, executor 의 호출이 완료되어야 promise 객체를 리턴한다.
    
- 끝까지 간다

**처리과정**

```
app.get('/hello', (req, res) => { // 해당 함수는
  res.set('Access-Control-Allow-Origin', '*'); //응답헤더 설정
  res.set('Content-Type', 'text/plain; charset=UTF-8'); //응답헤더 설정

  setTimeout(()=> {
    res.send("Hello!");
  }, 3000);
}); // 해당 함수는 3초가 지나지 않아도 즉시 종료되나  웹에 응답은 3초 후 > 그러면 요청 완료
```

![Untitled](promise%20&%20fetch%208a9b539294774262a6472b86d0a9a9c4/Untitled.png)

**promist 비동기 작업**

Promise 생성자는 작업 함수(executor) 호출이 끝나는 즉시 Promise 객체를 리턴한다.
⇒ 작업 함수에서 실행하는 비동기 작업이 끝날 때 까지 기다리지 않는다. ⇒ 벽돌화가 없다

### Promise - 비동기 작업의 완료를 통지하기

cf. AJAX 요청의 여러 용어

![Untitled](promise%20&%20fetch%208a9b539294774262a6472b86d0a9a9c4/Untitled%201.png)

```jsx
function onFulfilled() { // on으로 시작 함수: 어떤 이벤트로 인해 시작 'fulfilled에 대하여' 의미
  console.log("fulfilled!")
}

const promise = new Promise((resolve, reject) => {
  var xhr = new XMLHttpRequest();
  xhr.onreadystatechange = function() {
    if (xhr.readyState == 4) {
      console.log(xhr.responseText);
      resolve(); // 약속된 작업을 처리했다고 통지한다.
    }
  };
  xhr.open("GET", "http://localhost:3000/hello", true); 
  xhr.send();
});

// 작업 완료를 통보 받았을 때 호출될 함수를 등록한다.
// => resolve() 로 통지했을 때 호출
promise.then(onFulfilled); // 등록시 사용하는 메서드 .then

console.log("끝!");
```

### 비동기 작업을 실행하는 중에 오류가 발생했음을 통지하기

```jsx
const promise = new Promise((resolve, reject) => {
  var xhr = new XMLHttpRequest();
  xhr.onreadystatechange = function() {
    if (xhr.readyState == 4) {
      console.log(xhr.responseText);
      reject(); // 문제가 발생하여 약속된 작업을 거절한다고 알린다.
    }
  };
  xhr.open("GET", "http://localhost:3000/hello", true); 
  xhr.send();
});

console.log("끝!");

// executor로부터 작업 거절 통지를 받았을 때
// 그것을 처리할 함수가 등록되어 있지 않다면 
// 예외가 발생한다.
```

![Untitled](promise%20&%20fetch%208a9b539294774262a6472b86d0a9a9c4/Untitled%202.png)

### 작업 거절 통보를 받았을 때 수행할 함수를 등록하기

```jsx
function onRejected() {
  console.log("rejected!")
}
...
// executor로부터 작업 거절을 통지받았을 때 호출될 함수를 등록한다.
promise.then(undefined, onRejected);
```

![Untitled](promise%20&%20fetch%208a9b539294774262a6472b86d0a9a9c4/Untitled%203.png)

### promise 실행흐름

![Untitled](promise%20&%20fetch%208a9b539294774262a6472b86d0a9a9c4/Untitled%204.png)

### then(onFulfilled, onRejected)

```jsx
function onFulfilled() {
  console.log("fulfilled!")
}

function onRejected() {
  console.log("rejected!")
}

const promise = new Promise((resolve, reject) => {
  var xhr = new XMLHttpRequest();
  xhr.onreadystatechange = function() {
    if (xhr.readyState == 4) {
      console.log(xhr.responseText);
      
      resolve(); // 약속된 작업을 처리했다고 통지한다.
      // reject(); // 문제가 발생하여 약속된 작업을 거절한다고 알린다.
    }
  };
  xhr.open("GET", "http://localhost:3000/hello", true); 
  xhr.send();
});

console.log("끝!");

// 약속한 작업이 이행됐을 때 호출될 함수와 
// 약속한 작업이 거절됐을 때 호출될 함수를 한 번에 등록할 수 있다.
promise.then(onFulfilled, onRejected);
```

### then()의 리턴 값

Chain of Responsebility

: promise.then()으로 등록한 작업 함수의 실행이 끝난 후 다음 순서로 호출될 것이다.

```jsx
new Promise((resolve, reject) => {
  var xhr = new XMLHttpRequest();
  xhr.onreadystatechange = function() {
    if (xhr.readyState == 4) {
      console.log(xhr.responseText);
      
      resolve(); // 작업이 완료되었다고 통지한다.
    }
  };
  xhr.open("GET", "http://localhost:3000/hello", true); 
  xhr.send();
}) // 세미콜론 없음
.then(() => console.log("fulfilled...1"))
.then(() => console.log("fulfilled...2")) 
.then(() => console.log("fulfilled...3"))
.then(() => console.log("fulfilled...4"));

console.log("끝!");
```

![Untitled](promise%20&%20fetch%208a9b539294774262a6472b86d0a9a9c4/Untitled%205.png)

### Promise(executor)의 작업 결과 받기

```jsx

const promise = new Promise((resolve, reject) => {
  // Promise(executor)의 작업자가 직접 리턴한 것은 받을 수 없다.
  return "결과!";
});

----------------------------------------------------------------

const promise = new Promise((resolve, reject) => {
  // 작업 결과는 resolve()의 아규먼트로 전달해야 한다.
  resolve("결과!");
});

// promise가 처리한 작업 결과는 
// then(handler)으로 등록한 handler의 파라미터로 받는다.
promise.then((result) => console.log(result)); 
```

- 한개의 약속에 여러개의 함수 등록

![Untitled](promise%20&%20fetch%208a9b539294774262a6472b86d0a9a9c4/Untitled%206.png)

### Method Chaining 기법으로 then(handler)의 작업 결과 받기

```jsx
new Promise((resolve, reject) => { // 체이닝 연결에는 변수 필요 없다
  resolve("결과!");
})
.then((result) => {
  console.log(result)
  return result + " => 1";
})
.then((result) => {
  console.log(result)
  return result + " => 2";
})
.then((result) => {
  console.log(result)
  return result + " => 3";
})
.then((result) => console.log(result));

console.log("끝!");

// return 값의 의미 : 호출 받을 때 통제 받을 함수
```

![Untitled](promise%20&%20fetch%208a9b539294774262a6472b86d0a9a9c4/Untitled%207.png)

![Untitled](promise%20&%20fetch%208a9b539294774262a6472b86d0a9a9c4/Untitled%208.png)

### # 6 예외처리: then()

```jsx
const promise = new Promise((resolve, reject) => {
  throw '오류 발생!!!';
})
.then(() => console.log("fulfilled!"), 
      () => console.log("rejected!"));

console.log("끝!");

// executor에서 오류가 발생하면 
// then()으로 등록한 reject 함수가 호출된다.

... 

.catch(() => console.log("rejected!"));
// ==> then(undefined, onRejection) 과 동일하다.

...

promise.then(undefined, 
             () => console.log("rejected!"));
promise.catch(() => console.log("catched!"));

...

const promise = new Promise((resolve, reject) => {
  throw '오류 발생!!!';
})  // reject 핸들러가 없어서 .then으로 
.then(() => console.log("fulfilled!")) 
.catch(() => console.log("catched!"));
// then()이 리턴한 promise 에 오류 핸들러가 등록되어 있다면,
// 그 연결을 따라가서 오류 핸들러를 호출한다.
⬇
.then(() => console.log("fulfilled! - 1"))
.then(() => console.log("fulfilled! - 2"))
.then(() => console.log("fulfilled! - 3"))
.then(() => console.log("fulfilled! - 4"))
.catch(() => console.log("catched!"));
// 또한, then()이 리턴한 promise를 계속 따라가면서 예외 핸들러를 찾아 호출한다.

...

.then(() => console.log("fulfilled! - 1"))
.then(() => console.log("fulfilled! - 2"))
.catch(() => console.log("catched! - 1"))
.catch(() => console.log("catched! - 2"));
```

- 체인으로 연결된 promise는 예외를 처리할 때 까지 전달한다.
    
    따라서, 예외를 처리하면 전달을 멈춘다.
    

![# 중복 사용할 때](promise%20&%20fetch%208a9b539294774262a6472b86d0a9a9c4/Untitled%209.png)

# 중복 사용할 때

- **결론,  catch()는 한번만, 그리고 마지막에 둘 것**

### fetch() 사용하기

```jsx

var xhr = new XMLHttpRequest();
xhr.onreadystatechange = () => {
    if (xhr.readyState == 4 &&  xhr.status == 200) {
        var arr = JSON.parse(xhr.responseText);
        for (var b of arr) {
            var tr = document.createElement("tr");
            tr.innerHTML = "<td>" + b.no + "</td>" + 
            "<td>" + b.title + "</td>" + 
            "<td>" + b.writer + "</td>" +
            "<td>" + b.viewCnt + "</td>";
            tbody.appendChild(tr);
        }
    }

};

얘를 아래로 변경
```

```jsx
let promise = fetch("http://localhost:3000/boards");
promise.then(() => {
    console.log("서버로부터 응답 받았다");
});
```

1. fetch() URL 등록
2. response.text()
    
    응답에서 텍스트를 추출하여 객체로 deserialization을 수행하는 Promise 객체
    
3. .then()

```jsx
let promise = fetch("http://localhost:3000/boards");
let promise2 = promise.then((response) => {
   return response.text(); // 서버 응답내용을 text로 변환
});
promise2.then((text) => { // 약속 이행한 결과를 받음
    console.log(text);
});

⬇ 아래와 같이 줄일 수 있다
```

```jsx
fetch("http://localhost:3000/boards")
.then((response) => {
   return response.json(); 
})
.then((arr) => { 
    for (var b of arr) {
        var tr = document.createElement("tr");
        tr.innerHTML = "<td>" + b.no + "</td>" + 
        "<td>" + b.title + "</td>" + 
        "<td>" + b.writer + "</td>" +
        "<td>" + b.viewCnt + "</td>";
        tbody.appendChild(tr);
    }
});
```